<?php

namespace Dashboard\AssignmentBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TechToolsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TechToolsRepository extends EntityRepository
{
}
