<?php

namespace Dashboard\CourseBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AssignmentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AssignmentRepository extends EntityRepository
{
}
