default:
    pattern:  /
    defaults: { _controller: DashboardAssignmentBundle:Default:index }

dashboard_assignment:
    resource: "@DashboardAssignmentBundle/Controller/"
    type:     annotation
    prefix:   /

dashboard_new_user:
    resource: "@DashboardNewUserBundle/Controller/"
    type:     annotation
    prefix:   /

